insert into public.topics (title, description, sort_order) values
('Morning Light', 'Capture the soft golden light just after sunrise. Look for long shadows, warm glows, and the quiet beauty of early morning.', 1),
('Texture Hunt', 'Find and photograph interesting textures in the natural world — bark, stone, moss, soil, or anything that begs to be touched.', 2),
('Urban Green', 'Discover plants thriving in unexpected city spots — cracks in pavement, rooftop gardens, overgrown fences.', 3),
('Reflections', 'Hunt for reflections in puddles, windows, still water, or any shiny surface you find outside.', 4),
('Small World', 'Get close and photograph the miniature world at your feet — insects, tiny flowers, pebbles, or dewdrops.', 5),
('Shadows & Silhouettes', 'Use light and shadow to create dramatic shapes. Look for strong contrasts and interesting outlines.', 6),
('Color Pop', 'Find one bold, vibrant color in nature and make it the star of your photo.', 7),
('Symmetry', 'Seek out natural or man-made symmetry outdoors — leaves, architecture, reflections, paths.', 8),
('Sky Watching', 'Look up. Capture clouds, contrails, birds in flight, or the color gradient of the sky.', 9),
('Water in Motion', 'Photograph moving water — a stream, fountain, rain, or waves. Experiment with fast and slow shutter vibes.', 10),
('Patterns in Nature', 'Find repeating patterns — tiles, leaves, bricks, flowers, or anything that creates a rhythm.', 11),
('Wildlife Moment', 'Patiently wait and capture a bird, insect, squirrel, or any creature going about its day.', 12),
('Leading Lines', 'Use paths, fences, rivers, or roads to draw the eye into your photo.', 13),
('Decay & Renewal', 'Photograph something old, weathered, or decaying alongside signs of new life growing nearby.', 14),
('Golden Hour', 'Shoot during the hour before sunset. Capture the warm, orange-pink light transforming everything it touches.', 15),
('Framing', 'Use natural elements — branches, arches, doorways, or windows — to frame your subject.', 16),
('Lonely Object', 'Find a single object standing alone in a wide open space — a tree in a field, a bench in the park.', 17),
('Seasonal Signs', 'Document something that perfectly captures the current season — a specific flower, leaf, or weather pattern.', 18),
('Abstract Nature', 'Zoom in so close that natural objects become abstract shapes and colors rather than recognizable things.', 19),
('Human & Nature', 'Photograph the intersection of human-made structures and the natural world growing around them.', 20),
('Blue Hour', 'Head out just after sunset or before sunrise for the cool, moody blue light that lingers briefly.', 21),
('Overcast Magic', 'Use flat, diffused cloud light to reveal color and detail that harsh sun would wash out.', 22),
('Still Life Outside', 'Arrange a few natural objects you find — stones, leaves, flowers — and photograph them together.', 23),
('Motion Blur', 'Capture movement in nature — swaying grass, falling leaves, running water — with intentional blur.', 24),
('Negative Space', 'Use a large area of empty sky, water, or ground to make your subject stand out.', 25),
('Hidden Beauty', 'Find something most people walk past every day and reveal what makes it beautiful.', 26),
('Rain Day', 'Embrace the rain — photograph puddles, raindrops on leaves, wet streets, or people under umbrellas.', 27),
('Into the Wild', 'Venture to a green space — park, trail, garden — and capture the feeling of being in nature.', 28),
('Dusk to Dark', 'Stay out as daylight fades. Capture the changing mood as artificial lights begin to glow.', 29),
('Your Neighborhood', 'Find something beautiful, strange, or interesting within a 5-minute walk of where you are right now.', 30);
